### ISSUE TITLE
ResearchProjects_Server.xml Glitterworld typo in Research menu

### ISSUE THREAD

**Issue by IffyChan** [Georodin/ACS-AdvancedCommercialServer#1]
<ServerGlitterworld.label>server advanced</ServerGlitterworld.label>
  <ServerGlitterworld.description>Construct a Server Rack and basic Servers to fill it.</ServerGlitterworld.description>
  
  
![image](https://github.com/Georodin/ACS-AdvancedCommercialServer/assets/25159352/86126d83-9cf2-49b8-86c9-b21091b20e05)

**Comment by Georodin** [comment]
thanks, is fixed now
